### ISSUE TITLE
Add RBAC support for metrics view

### ISSUE THREAD

**Issue by dlampsi** [robinhood/airflow-prometheus-exporter#5]
Hi.
Can you please add RBAC support for the metrics view?
I can't push new branches to this repo, but I modified locally your plugin and it works well on 1.10.5 with these changes:
```python
from airflow.settings import RBAC
```

```python
if RBAC:
    from flask_appbuilder import BaseView as FABBaseView, expose as FABexpose

    class RBACMetrics(FABBaseView):
        route_base = "/admin/metrics/"
        @FABexpose('/')
        def list(self):
            return Response(generate_latest(), mimetype='text')

    # Metrics View for Flask app builder used in airflow with rbac enabled
    RBACmetricsView = {
        "view": RBACMetrics(),
        "name": "metrics",
        "category": "Admin"
    }

    ADMIN_VIEW = []
    RBAC_VIEW = [RBACmetricsView]

else:
    class Metrics(BaseView):
        @expose('/')
        def index(self):
            return Response(generate_latest(), mimetype='text/plain')

    ADMIN_VIEW = [Metrics(category="Prometheus exporter", name="metrics")]
    RBAC_VIEW = []

class AirflowPrometheusPlugin(AirflowPlugin):
    """Airflow Pluging for collecting metrics."""

    name = 'airflow_prometheus_plugin'
    operators = []
    hooks = []
    executors = []
    macros = []
    admin_views = [ADMIN_VIEW]
    flask_blueprints = []
    menu_links = []
    appbuilder_views = [RBAC_VIEW]
    appbuilder_menu_items = []
```

**Comment by abhishekray07** [comment]
Hey!

Feel free to submit a pull request and I can took a look!

**Comment by dlampsi** [comment]
> Hey!
> 
> Feel free to submit a pull request and I can took a look!

Sorry, but as I said previously - I can't push the new branch to this repository and as a result I can’t create PR.

**Comment by abhishekray07** [comment]
You should be able to create PR by forking this repo and making changes your forked version and submitting a pull request. More details available here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

You shouldn't need access to push to this repo to be able to create a PR.

**Comment by dlampsi** [comment]
@abhishekray07 probably @Shini31 created PR faster than me and also do some bug fix, so I closed my PR. I suppose you should check #6.
