### ISSUE TITLE
Add up metric for airfow process

### ISSUE THREAD

**Issue by mcinquin** [robinhood/airflow-prometheus-exporter#7]
Hello,

Do you think it would be possible to add _up_ metric for the different process of Airflow?
- scheduler
- webserver
- worker

Regards.

**Comment by abhishekray07** [comment]
Hey,

We already have a metric that can be used as a proxy for scheduler health (scheduler delay). The Airflow statsd metric also emits a scheduler health metric which basically the up metric for the scheduler (https://airflow.apache.org/metrics.html).

The exporter only communicates with the Airflow Metadata database to compute the metrics. There are other potential ways to figure out if the webserver and worker are running. 

Feel free to comment with your ideas or submit a PR and we can discuss further.
