### ISSUE TITLE
Add Airflow Health Status

### ISSUE THREAD

**Issue by mcinquin** [robinhood/airflow-prometheus-exporter#8]
Hello,

Do you think it would be possible to add an health status metric based on https://airflow.readthedocs.io/en/stable/howto/check-health.html ?

Regards.

**Comment by abhishekray07** [comment]
Hey,
We have been using the scheduler delay metric (https://github.com/robinhood/airflow-prometheus-exporter/blob/master/airflow_prometheus_exporter/prometheus_exporter.py#L202) as a proxy for scheduler health internally and that has worked pretty well for us.

If you have other ideas on what metrics would be useful, feel free to submit a PR.
